### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/aws-utils#4]
Hi @sucksido !

Now that things are starting to pick up pace, we need to document all the steps so that we can reproduce them in the future. Can you open a google document in the shared folder and start writing down the documentation for deploying Ersilia Models as ECS instances - I'd like to try and reproduce the pipeline next week.

We will think in the future where can we move this documentation more permanently

**Comment by sucksido** [comment]
@GemmaTuron this has been noted, I will start documenting the processes

**Comment by sucksido** [comment]
I have shared the Google doc with the team, i will make making updates as I progress

**Comment by GemmaTuron** [comment]
Hi @sucksido 

I cannot see where this document is. Please make sure to add it to our shared Drive folder so we can all collaborate there.

**Comment by sucksido** [comment]
HI @GemmaTuron , Please assist with moving the document to the right folder, I can't seem to navigate to the folder structure.

Document: [](https://docs.google.com/document/d/1sw4sPH9uSYREv_6uvdL8W0XMpREFomgu0L8TwSZZZGE/edit)

**Comment by GemmaTuron** [comment]
Hello @sucksido 
I cannot access this document. In any case, the Drive issues with your email should be solved, please refer to Nicola if they are not - she managed. You should be able to find the Documentation folder in the shared folder and drop the document there yourself

**Comment by sucksido** [comment]
Document: https://docs.google.com/document/d/1r5tD1_vkeOwHiLszXGSrlysy2pb9mKtpWpDoqU64fFg/edit

**Comment by sucksido** [comment]
![image](https://github.com/ersilia-os/aws-utils/assets/8820397/237f31e7-c552-4938-a994-89d160b3f4f3)
![image](https://github.com/ersilia-os/aws-utils/assets/8820397/ba5dba88-14b6-4f22-bd03-f68661f9db8a)
I have managed to sign in with my H3D email and this is what Im seeing, still can't see the folders

**Comment by GemmaTuron** [comment]
Hi @sucksido 
Try it again now, it should work

**Comment by sucksido** [comment]
Thanks @GemmaTuron 

![image](https://github.com/ersilia-os/aws-utils/assets/8820397/10c18722-e2c7-4ebb-9ae9-644332990309)

**Comment by sucksido** [comment]
Document should be up and accessible

**Comment by sucksido** [comment]
https://docs.google.com/document/d/1nqOKVwmbhpKQvYQfdar77jj7B0uBBCdDgMQhZPx6NyE/edit
